sudo: true
language: rust
rust:
- nightly
- beta
- stable
matrix:
  allow_failures:
  - rust: nightly
before_script:
- ! 'pip install ''travis-cargo<0.2'' --user &&
  export PATH=$HOME/.local/bin:$PATH;
  wget https://github.com/jedisct1/libsodium/releases/download/1.0.3/libsodium-1.0.3.tar.gz;
  tar xvfz libsodium-1.0.3.tar.gz;
  cd libsodium-1.0.3 && ./configure --prefix=/usr && make && sudo make install && cd ..
'
script:
- ! 'travis-cargo build &&
  travis-cargo build -- --features "crypto" &&
  travis-cargo test -- --features "crypto" &&
  travis-cargo bench -- --features "crypto" &&
  travis-cargo --only stable doc -- --features "crypto"
'
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
after_success:
- travis-cargo --only stable doc-upload -- --features "crypto"
- travis-cargo coveralls --no-sudo -- --features "crypto"
notifications:
  email:
    on_success: never
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
