[package]
name = "ethcloud"
version = "0.1.0"
authors = ["Dennis Schwerdel <schwerdel@informatik.uni-kl.de>"]
build = "build.rs"

[dependencies]
time = "0.1"
docopt = "0.6"
rustc-serialize = "0.3"
log = "*"
env_logger = "*"

[build-dependencies]
gcc = "0.3"
