[package]
name = "vpncloud"
version = "0.1.0"
authors = ["Dennis Schwerdel <schwerdel@informatik.uni-kl.de>"]
build = "build.rs"

[dependencies]
time = "0.1"
docopt = "0.6"
rustc-serialize = "0.3"
log = "0.3"
epoll = "0.2"
signal = "0.1"
nix = "*"
libc = "*"
libsodium-sys = {version = "0.0.9", optional = true}

[build-dependencies]
gcc = "0.3"

[features]
default = []
crypto = ["libsodium-sys"] #not default as it requires external library
bench = []
